plugins:
    csslint:
      enabled: true
# ignore files 
exclude_patterns:
  - module/badges.js
  - module/assets/backgroundColor.js
  - module/sidebar.js
  - module/fizzTester.js
  - module/assets/singlePokemon.js
  - module/pokeApi.js
  - module/randomPoke.js